ROR capstone project 'Budget App'
mohamedgamaleldin999999/the-budget-app pull request #7
Opened 2024-02-23 00:17 UTC by mohamedgamaleldin999999

Description: 💬
This pull request for illustrate what I've done to finish the budget mobile app using RoR

Done: ✅
 Create a rails project

 Setup the linters, rubocop & styleint

 Setup the devise for authentication

 Added the navbar

 Setup the home page

 Setup bootstrap

 Create groups table

 Create deal table

 Adding the references between tables

 Create the data models for deals and groups, and set up the relationships between them.

 Create the controllers and views for deals and groups, and set up the routes.

 Add the deals and groups index and new views.

 Add the create, index, and show actions to the deals and groups controllers.

 Update the deals and groups tables to add the required columns and foreign keys.

 Add the splash controller and view, and set up the routes.

 Setup and Using Rspec for test

 Implement different test for different components to ensure it's consistency.

 Adding README

Documentation: [Presentation video](https://youtu.be/KgvMz6qQD24)

2024-02-23 00:37 UTC, Reem-lab commented
- Could you check your slack?

2024-02-23 01:26 UTC, Efiamotu-1 requested changes
Hi @mohamedgamaleldin999999, 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-23 01:26 UTC, Efiamotu-1 commented on README.md
- [ ] Your readme is currently missing an important project requirement as shown in the image below, please kindly record this video and add it to your readme before resubmitting :+1: 
![pr](https://github.com/mohamedgamaleldin999999/the-budget-app/assets/89055502/1fc04ea7-6a93-40f4-9fda-00ac77dc71c8)

2024-02-23 01:26 UTC, Efiamotu-1 commented on README.md
> +- [Live Demo Link]()
- [ ] Your live demo is also missing and this is an important requirement for this project please kindly add it before resubmit :+1:

2024-02-23 01:26 UTC, Efiamotu-1 commented on app/views/layouts/application.html.erb
- [ ] The button on the transaction page should read `Add New Transaction` not `new deal` please kindly correct this
 
![tp](https://github.com/mohamedgamaleldin999999/the-budget-app/assets/89055502/b17b4725-47f1-40b8-b774-e99585cc1164)

2024-02-23 01:26 UTC, Efiamotu-1 commented on app/views/layouts/application.html.erb
- [ ] You are missing this below requirement for your transactions page, please kindly fix it 
![rew](https://github.com/mohamedgamaleldin999999/the-budget-app/assets/89055502/f6bd64f2-8101-464b-a6c4-dd6e32d6a091)

2024-02-23 01:26 UTC, Efiamotu-1 commented on app/controllers/deals_controller.rb
[OPTIONAL]
- [ ] In all of your controllers you didn't create methods to handle update and destry action, i kindly advise that you add them to your project

2024-02-23 01:26 UTC, Efiamotu-1 commented on app/controllers/deals_controller.rb
- [ ] YOu currently have two tests failing at the moment as shown in the image below, please kindly fix them :+1: :sparkles: 
![fl](https://github.com/mohamedgamaleldin999999/the-budget-app/assets/89055502/1060e154-a685-4cba-90c3-81fe2f3437d1)

2024-02-25 03:11 UTC, OyePriscilla requested changes
Hi @mohamedgamaleldin999999  👏 👏 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Live demo work properly
Designed transaction page according to the given template

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-25 03:11 UTC, OyePriscilla commented on README.md
- [ ] Please kindly make a video presentation as suggested earlier in accordance to the project requirement. 🙏

2024-02-25 03:11 UTC, OyePriscilla commented on spec/views/transactions_spec.rb
Some of the tests written that were passing in previous commit are now failing, perhaps due to the new implementation done. Kindly fix this. 🙏 

<img width="596" alt="Untitled" src="https://github.com/mohamedgamaleldin999999/the-budget-app/assets/103386183/94c813a3-a960-4850-af5b-733f341125ba">

2024-02-25 04:31 UTC, mohamedgamaleldin999999 commented
Here's my documentation:

[Presentation video](https://youtu.be/KgvMz6qQD24)

2024-02-25 04:43 UTC, topeogunleye approved these changes
Hi @mohamedgamaleldin999999, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

> ## (Highlights) Good Points: 💪 
> * Added presentation video according to project requirements :heavy_check_mark:

![çrpik-kurdî-impressive](https://user-images.githubusercontent.com/52934128/180656067-c6788183-0594-4658-94e3-3d2523b6db08.gif)



Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear
Please, remember to tag @topeogunleye in your question so I can receive the notification.
 
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-02-26 00:11 UTC, merged